name: Poetry

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pip install -U pip poetry

      - name: Remove Lock File
        continue-on-error: true
        run: rm poetry.lock

      - name: Install Dependencies & Build Lock File
        run: poetry install

      - name: Setup Git
        run: git config user.name "Automated poetry.lock Updater"

      - name: Push To GitHub
        continue-on-error: true
        run: |
          git pull
          git add ./
          git commit -m "Updated poetry.lock"
          git push
