name: PyRight

on:
  - pull_request
  - push

jobs:
  pyright:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyRight & Dependencies
        run: |
          pip install -U pip pyright poetry
          poetry install --no-dev

      - name: Run PyRight
        run: poetry run pyright ./
